apiVersion: v1
kind: Service
metadata:
  name: image-recognition
  labels:
    app: image-recognition
spec:
  type: LoadBalancer
  selector:
    app: image-recognition
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000
    protocol: TCP
